services:
  postgres_test:
    image: postgres:14-alpine
    restart: always
    env_file:
      - ./backend/.env.test
    ports:
      - 5433:5432
    volumes:
      - db-data-test:/var/lib/postgresql/data

volumes:
  db-data-test: